### ISSUE TITLE
Ambassador profile view/edit page

### ISSUE THREAD

**Issue by shauminn-colab** [colab-coop/hello-voter#143]
As an ambassador, I want to be able to view my profile informationed entered at signup and make changes any time.

- Add a person icon on the top navigation to the right of the Help (question mark) icon, or beneath it on mobile menu
- Clicking the person icon opens the ambassador's profile page. The profile page should replicate the /ambassador/signup form and allow the ambassador to make any changes to their profile that they choose. All fields are required on this form and we should show the same error messages we show on /ambassador/signup for empty fields or validation errors

**Comment by shauminn-colab** [comment]
@cooperka - This is looking great so far - i Just have a few notes:
1)  Can we show any errors that we hit when we submit this? It seems like it silently fails when the address isn't recognized by census API but user doesn't know it failed until they go back to Profile page
2) Can we check that only ALLOWED_STATES (backend env var) are allowed to be submitted here as on signup?

**Comment by cooperka** [comment]
Those both should already be working; I saw errors (including for ALLOWED_STATES) when I tested locally. Did you have these issues on staging2? I can check on it later today and see what's up!

**Comment by cooperka** [comment]
(indeed it's not throwing errors at all on staging, the request is successful and profile gets updated to an illegal address. Will diagnose later)

**Comment by shauminn-colab** [comment]
thanks :)

**Comment by cooperka** [comment]
(Well there's no way that I actually tested this validation logic, because it isn't implemented! I must have been on the signup page by mistake.)

`va/ambassadors#signup` does SMS validation and carrier lookup; `services/ambassadors#signup` does data normalization, string validation, and address checking afterward. In order to implement a safe user update endpoint, these steps will need to be modularized and shared with `va/ambassadors#updateCurrentAmbassador`. To simplify things, we could at least **disallow changing your SMS number from the profile page**?

I can work on this small refactor this week assuming it sounds like a good use of time. FYI if this is blocking any sort of release, we could simply **hide** the "Profile" link from the nav menu and the app would be as safe as it currently is (the `PUT /ambassadors/current` endpoint is public so any user could use it right now anyway).

**Comment by shauminn-colab** [comment]
Thanks Kevin!  Let me check on removing phone number from profile page, and yes it makes sense that we can hide profile link in the interim while this is worked on.
